// WRISTO 40-Watch Product Catalog & Editorial Collections
// Source of truth: docs/40_images_2.png & docs/40_images_watches.png

const PRODUCTS = [
  {
    id: "WRT-001",
    num: "01",
    brand: "AUREN",
    model: "Atlas Black",
    price: 4999,
    originalPrice: 6499,
    rating: 4.8,
    reviewsCount: 142,
    image: "./assets/products/watch-01.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Minimal",
    caseSize: "40mm",
    strap: "Black Leather",
    dial: "Matte Black",
    material: "Stainless Steel",
    waterResistance: "50m",
    badge: "Best Seller",
    tagline: "Stripped-back monochrome precision for modern minimalism.",
    description: "The AUREN Atlas Black strips horology down to its purest essentials. Featuring an ultra-slim 40mm surgical-grade stainless steel case finished in brushed obsidian, an unblemished matte black dial with hairline indices, and a supple vegetable-tanned Italian calfskin strap.",
    aiMatchScore: 98,
    aiReason: "Understated obsidian aesthetic pairs seamlessly with both monochrome tailored suiting and minimalist weekend wear.",
    occasion: ["Office", "Casual", "Weekend"],
    colors: ["#111111", "#4A4A4A"]
  },
  {
    id: "WRT-002",
    num: "02",
    brand: "AUREN",
    model: "Meridian Silver",
    price: 5499,
    originalPrice: 6999,
    rating: 4.7,
    reviewsCount: 98,
    image: "./assets/products/watch-02.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Classic",
    caseSize: "41mm",
    strap: "Silver Mesh",
    dial: "Sunray Silver",
    material: "Stainless Steel",
    waterResistance: "50m",
    badge: "Trending",
    tagline: "Fluid Milanese elegance reflecting metropolitan light.",
    description: "Crafted for those who appreciate understated brilliance, the Meridian Silver pairs an architectural sunray silver dial with a fluid Milanese mesh strap that adjusts smoothly to any wrist size.",
    aiMatchScore: 94,
    aiReason: "High-luminance silver finish complements formal shirting while offering breathable mesh comfort for all-day desk wear.",
    occasion: ["Formal", "Office"],
    colors: ["#E0E0E0", "#FFFFFF"]
  },
  {
    id: "WRT-003",
    num: "03",
    brand: "AUREN",
    model: "Heritage Gold",
    price: 6999,
    originalPrice: 8999,
    rating: 4.9,
    reviewsCount: 215,
    image: "./assets/products/watch-03.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Dress",
    caseSize: "39mm",
    strap: "Rich Brown Leather",
    dial: "Champagne Gold",
    material: "Gold PVD Steel",
    waterResistance: "30m",
    badge: "Luxury Pick",
    tagline: "Warm champagne tones reminiscent of vintage heirloom timepieces.",
    description: "With its warm champagne sunburst dial, hand-polished gold PVD case, and deep mahogany alligator-grain leather strap, the Heritage Gold embodies timeless mid-century poise.",
    aiMatchScore: 92,
    aiReason: "Rich warm gold dial harmonizes with earth-toned outerwear, blazers, and evening dress codes.",
    occasion: ["Formal", "Luxury", "Evening"],
    colors: ["#C89B5B", "#8B4513"]
  },
  {
    id: "WRT-004",
    num: "04",
    brand: "AUREN",
    model: "Edge Blue",
    price: 4499,
    originalPrice: 5999,
    rating: 4.6,
    reviewsCount: 76,
    image: "./assets/products/watch-04.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Casual",
    caseSize: "42mm",
    strap: "Midnight Blue Leather",
    dial: "Sunray Royal Blue",
    material: "Stainless Steel",
    waterResistance: "50m",
    badge: "New",
    tagline: "Deep ocean contrast that catches ambient light with subtlety.",
    description: "The Edge Blue showcases an electric royal blue sunray dial framed in a sharp chamfered bezel. Designed as a daily driver with elevated character.",
    aiMatchScore: 90,
    aiReason: "Vibrant royal dial adds a tasteful pop of contrast to neutral outfits without looking loud.",
    occasion: ["Casual", "Weekend", "Office"],
    colors: ["#1B365D", "#2C3E50"]
  },
  {
    id: "WRT-005",
    num: "05",
    brand: "AUREN",
    model: "Regent Green",
    price: 14999,
    originalPrice: 18999,
    rating: 4.9,
    reviewsCount: 310,
    image: "./assets/products/watch-05.png",
    category: "Men",
    gender: "Men",
    movement: "Automatic",
    style: "Premium",
    caseSize: "41mm",
    strap: "Solid Link Steel",
    dial: "Emerald Green",
    material: "316L Stainless Steel",
    waterResistance: "100m",
    badge: "Editorial Choice",
    tagline: "Lush emerald lacquer dial driven by an exhibition-back automatic caliber.",
    description: "The flagship of the Auren line. Featuring an exhibition caseback revealing an automatic movement with a 42-hour power reserve, sapphire crystal, and an intoxicating deep forest emerald dial.",
    aiMatchScore: 96,
    aiReason: "High-spec automatic movement paired with a coveted green dial that makes a subtle yet unmistakable statement of refinement.",
    occasion: ["Formal", "Luxury", "Office"],
    colors: ["#1C432E", "#D4AF37"]
  },
  {
    id: "WRT-006",
    num: "06",
    brand: "AUREN",
    model: "Chrono Steel",
    price: 8999,
    originalPrice: 11499,
    rating: 4.8,
    reviewsCount: 184,
    image: "./assets/products/watch-06.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Chronograph",
    caseSize: "43mm",
    strap: "Stainless Steel",
    dial: "Tri-Compax Black",
    material: "Stainless Steel",
    waterResistance: "100m",
    badge: "Popular",
    tagline: "Instrument-grade tri-compax chronograph with tactile pushers.",
    description: "Engineered with three precision sub-dials measuring 24 hours, minutes, and split-seconds. The solid brushed 3-link bracelet gives it a commanding presence on the wrist.",
    aiMatchScore: 91,
    aiReason: "Provides sporty functionality with a clean executive aesthetic suitable for meetings and travel.",
    occasion: ["Travel", "Office", "Weekend"],
    colors: ["#111111", "#B0B0B0"]
  },
  {
    id: "WRT-007",
    num: "07",
    brand: "AUREN",
    model: "Terra Brown",
    price: 5999,
    originalPrice: 7499,
    rating: 4.7,
    reviewsCount: 88,
    image: "./assets/products/watch-07.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Casual",
    caseSize: "40mm",
    strap: "Espresso Leather",
    dial: "Warm Terra Brown",
    material: "Rose Gold PVD Steel",
    waterResistance: "50m",
    badge: "Staff Pick",
    tagline: "Warm mocha accents crafted for autumnal layers and casual suiting.",
    description: "A rich tobacco dial matched with warm bronze-gold hardware and handcrafted textured leather. Perfect for coffee shop work sessions or evening dinner dates.",
    aiMatchScore: 89,
    aiReason: "Earthy tones lend an organic, tactile warmth to linen shirts and casual knitwear.",
    occasion: ["Casual", "Weekend"],
    colors: ["#4E2E1E", "#B08D6B"]
  },
  {
    id: "WRT-008",
    num: "08",
    brand: "AUREN",
    model: "Eclipse Black",
    price: 7499,
    originalPrice: 9499,
    rating: 4.8,
    reviewsCount: 120,
    image: "./assets/products/watch-08.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Dress",
    caseSize: "40mm",
    strap: "Black Mesh Steel",
    dial: "Deep Obsidian",
    material: "PVD Matte Black",
    waterResistance: "50m",
    badge: "Limited",
    tagline: "Shadowy all-black silhouette engineered for cocktail hours.",
    description: "Every millimeter of the Eclipse Black is treated with a durable matte DLC coating. The pitch-black dial reflects only the subtlest glint on the polished faceted hour hands.",
    aiMatchScore: 93,
    aiReason: "Flawless stealth profile that disappears under tuxedo cuffs while commanding attention upon closer glance.",
    occasion: ["Evening", "Luxury", "Formal"],
    colors: ["#0F0F0F", "#2A2A2A"]
  },
  {
    id: "WRT-009",
    num: "09",
    brand: "VELA",
    model: "Luna Pearl",
    price: 5999,
    originalPrice: 7999,
    rating: 4.9,
    reviewsCount: 167,
    image: "./assets/products/watch-09.png",
    category: "Women",
    gender: "Women",
    movement: "Quartz",
    style: "Dress",
    caseSize: "34mm",
    strap: "Two-Tone Rose & Silver",
    dial: "Mother of Pearl",
    material: "Rose Gold & Steel",
    waterResistance: "30m",
    badge: "Best Seller",
    tagline: "Iridescent mother-of-pearl dial framed in alternating two-tone links.",
    description: "The Luna Pearl reflects soft opalescent hues from its natural mother-of-pearl dial. Completed with a dual-finish jubilee-style metal band that doubles as fine jewelry.",
    aiMatchScore: 97,
    aiReason: "Exquisite two-tone versatility coordinates effortlessly with both gold and silver jewelry collections.",
    occasion: ["Formal", "Luxury", "Special Events"],
    colors: ["#E8C89A", "#D3D3D3"]
  },
  {
    id: "WRT-010",
    num: "10",
    brand: "VELA",
    model: "Roseline",
    price: 6499,
    originalPrice: 8299,
    rating: 4.8,
    reviewsCount: 140,
    image: "./assets/products/watch-10.png",
    category: "Women",
    gender: "Women",
    movement: "Quartz",
    style: "Fashion",
    caseSize: "36mm",
    strap: "Powder Pink Leather",
    dial: "Pastel Rose",
    material: "Rose Gold PVD Steel",
    waterResistance: "30m",
    badge: "Trending",
    tagline: "Soft blush undertones and sculpted rose gold lugs.",
    description: "Delicate yet resilient. The Roseline features a matte blush pink dial with slim diamond-cut hands and a buttery-soft Italian calfskin strap in complementary pastel tones.",
    aiMatchScore: 93,
    aiReason: "Gentle pastel palette pairs naturally with spring/summer florals and light neutral wardrobes.",
    occasion: ["Casual", "Weekend", "Brunch"],
    colors: ["#F0DDD0", "#C89B5B"]
  },
  {
    id: "WRT-011",
    num: "11",
    brand: "VELA",
    model: "Elara Silver",
    price: 4999,
    originalPrice: 6299,
    rating: 4.7,
    reviewsCount: 89,
    image: "./assets/products/watch-11.png",
    category: "Women",
    gender: "Women",
    movement: "Quartz",
    style: "Minimal",
    caseSize: "36mm",
    strap: "Silver Milanese Mesh",
    dial: "Pure Silver Sunburst",
    material: "Stainless Steel",
    waterResistance: "30m",
    badge: "Clean Style",
    tagline: "Ultra-slim profile that sits like a second skin on delicate wrists.",
    description: "A masterclass in modern Scandinavian restraint. The Elara Silver measures just 6.8mm in case thickness, ensuring seamless sliding under knitwear and blouses.",
    aiMatchScore: 95,
    aiReason: "Clean silver architectural silhouette fits modern office dress codes with zero fuss.",
    occasion: ["Office", "Casual"],
    colors: ["#D8D8D8", "#F5F5F5"]
  },
  {
    id: "WRT-012",
    num: "12",
    brand: "VELA",
    model: "Celeste Blue",
    price: 5499,
    originalPrice: 6999,
    rating: 4.8,
    reviewsCount: 112,
    image: "./assets/products/watch-12.png",
    category: "Women",
    gender: "Women",
    movement: "Quartz",
    style: "Casual",
    caseSize: "34mm",
    strap: "Sky Blue Leather",
    dial: "Ice Blue Minimal",
    material: "Polished Steel",
    waterResistance: "30m",
    badge: "New Arrival",
    tagline: "Breezy glacial blue accents inspired by alpine skies.",
    description: "Featuring a serene ice-blue dial that evokes calm clarity. The pastel powder-blue strap is secured with a polished steel pin buckle for all-day comfort.",
    aiMatchScore: 91,
    aiReason: "Bright pastel touch enlivens denim, white linen, and contemporary casual looks.",
    occasion: ["Casual", "Weekend"],
    colors: ["#A4C8E1", "#FFFFFF"]
  },
  {
    id: "WRT-013",
    num: "13",
    brand: "VELA",
    model: "Aurelia Gold",
    price: 8499,
    originalPrice: 10999,
    rating: 4.9,
    reviewsCount: 198,
    image: "./assets/products/watch-13.png",
    category: "Women",
    gender: "Women",
    movement: "Quartz",
    style: "Premium",
    caseSize: "32mm",
    strap: "5-Link Gold Bracelet",
    dial: "Champagne Guilloché",
    material: "18K Gold PVD Steel",
    waterResistance: "50m",
    badge: "Luxury Pick",
    tagline: "Fine jewelry watchmaking featuring an intricate guilloché dial texture.",
    description: "The Aurelia Gold is a celebration of opulence. Its compact 32mm case is adorned with a textured sunburst dial and paired with a jewelry-style 5-link bracelet.",
    aiMatchScore: 96,
    aiReason: "Functions as a high-end statement bracelet that anchors evening gowns and cocktail attire.",
    occasion: ["Luxury", "Evening", "Formal"],
    colors: ["#C89B5B", "#E8C89A"]
  },
  {
    id: "WRT-014",
    num: "14",
    brand: "VELA",
    model: "Ivory Pearl",
    price: 6999,
    originalPrice: 8799,
    rating: 4.7,
    reviewsCount: 94,
    image: "./assets/products/watch-14.png",
    category: "Women",
    gender: "Women",
    movement: "Quartz",
    style: "Dress",
    caseSize: "35mm",
    strap: "Cream Beige Leather",
    dial: "Warm Ivory",
    material: "Gold PVD Steel",
    waterResistance: "30m",
    badge: "Staff Pick",
    tagline: "Warm tonal neutral that radiates quiet luxury.",
    description: "Warm ivory dial encased in a softly rounded champagne bezel, paired with a buttery cream leather band that develops a rich natural patina over time.",
    aiMatchScore: 94,
    aiReason: "Perfect tonal complement for the trending 'Quiet Luxury' aesthetic and neutral cashmere palettes.",
    occasion: ["Office", "Weekend", "Brunch"],
    colors: ["#F6F1E9", "#D9C9B8"]
  },
  {
    id: "WRT-015",
    num: "15",
    brand: "VELA",
    model: "Nova Mesh",
    price: 4799,
    originalPrice: 5999,
    rating: 4.6,
    reviewsCount: 82,
    image: "./assets/products/watch-15.png",
    category: "Women",
    gender: "Women",
    movement: "Quartz",
    style: "Fashion",
    caseSize: "36mm",
    strap: "Gunmetal Mesh",
    dial: "Midnight Black",
    material: "Gunmetal Ion Plating",
    waterResistance: "30m",
    badge: "Trending",
    tagline: "Moody gunmetal contrast designed for modern city streets.",
    description: "Dark, sleek, and contemporary. The Nova Mesh marries gunmetal ion plating with an inky dial and polished indices that gleam under neon evening lights.",
    aiMatchScore: 90,
    aiReason: "Edgy metropolitan vibe that transitions seamlessly from co-working desk to rooftop drinks.",
    occasion: ["Casual", "Evening"],
    colors: ["#333333", "#171717"]
  },
  {
    id: "WRT-016",
    num: "16",
    brand: "VELA",
    model: "Siena Rose",
    price: 5999,
    originalPrice: 7499,
    rating: 4.8,
    reviewsCount: 153,
    image: "./assets/products/watch-16.png",
    category: "Women",
    gender: "Women",
    movement: "Quartz",
    style: "Classic",
    caseSize: "35mm",
    strap: "Rose Gold Mesh",
    dial: "Sunray Rose",
    material: "Rose Gold Steel",
    waterResistance: "30m",
    badge: "Popular",
    tagline: "All-rose metallic harmony that glows warmly on all skin tones.",
    description: "A continuous flow of warm rose gold from bezel to Milanese mesh. The dial features subtle radially brushed grain that catches daylight effortlessly.",
    aiMatchScore: 92,
    aiReason: "Universally flattering rose warmth that elevates basic tees as easily as cocktail dresses.",
    occasion: ["Casual", "Formal", "Office"],
    colors: ["#D8B58A", "#F0DDD0"]
  },
  {
    id: "WRT-017",
    num: "17",
    brand: "ORBITA",
    model: "Core Black",
    price: 3999,
    originalPrice: 4999,
    rating: 4.7,
    reviewsCount: 165,
    image: "./assets/products/watch-17.png",
    category: "Unisex",
    gender: "Unisex",
    movement: "Quartz",
    style: "Minimal",
    caseSize: "38mm",
    strap: "Matte Silicone",
    dial: "Pitch Black",
    material: "Polymer & Steel",
    waterResistance: "50m",
    badge: "Essential",
    tagline: "Featherweight utilitarian watch built for effortless daily rotation.",
    description: "ORBITA's iconic Bauhaus-inspired daily watch. At just 42 grams, the Core Black features an ergonomic medical-grade silicone strap and high-contrast clean hands.",
    aiMatchScore: 93,
    aiReason: "Extremely lightweight and budget-friendly daily beater that maintains high design credibility.",
    occasion: ["Casual", "Weekend", "Active"],
    colors: ["#111111", "#222222"]
  },
  {
    id: "WRT-018",
    num: "18",
    brand: "ORBITA",
    model: "Mono Steel",
    price: 4499,
    originalPrice: 5699,
    rating: 4.8,
    reviewsCount: 130,
    image: "./assets/products/watch-18.png",
    category: "Unisex",
    gender: "Unisex",
    movement: "Quartz",
    style: "Minimal",
    caseSize: "39mm",
    strap: "Brushed Steel Bracelet",
    dial: "Polar Silver",
    material: "Stainless Steel",
    waterResistance: "50m",
    badge: "Popular",
    tagline: "Industrial monochromatic purity inspired by brutalist architecture.",
    description: "All-metal construction with horizontal satin brushing across case and integrated bracelet. A minimalist sculpture for your wrist.",
    aiMatchScore: 92,
    aiReason: "Brutalist all-steel aesthetic delivers maximum design punch per rupee.",
    occasion: ["Office", "Casual"],
    colors: ["#C0C0C0", "#E0E0E0"]
  },
  {
    id: "WRT-019",
    num: "19",
    brand: "ORBITA",
    model: "Field Olive",
    price: 4999,
    originalPrice: 6299,
    rating: 4.6,
    reviewsCount: 78,
    image: "./assets/products/watch-19.png",
    category: "Unisex",
    gender: "Unisex",
    movement: "Quartz",
    style: "Casual",
    caseSize: "40mm",
    strap: "Tactical Olive Canvas",
    dial: "Army Olive",
    material: "Matte Steel",
    waterResistance: "100m",
    badge: "Outdoor",
    tagline: "Rugged military canvas strap with high-visibility dial markers.",
    description: "Built for urban explorers and backcountry wanderers alike. The reinforced canvas webbing strap withstands rain, grit, and heavy use.",
    aiMatchScore: 88,
    aiReason: "Earthy military green works exceptionally well with denim, utility jackets, and hiking gear.",
    occasion: ["Outdoor", "Weekend", "Travel"],
    colors: ["#3D4A39", "#242424"]
  },
  {
    id: "WRT-020",
    num: "20",
    brand: "ORBITA",
    model: "Urban Sand",
    price: 4799,
    originalPrice: 5999,
    rating: 4.7,
    reviewsCount: 92,
    image: "./assets/products/watch-20.png",
    category: "Unisex",
    gender: "Unisex",
    movement: "Quartz",
    style: "Lifestyle",
    caseSize: "39mm",
    strap: "Sand Nubuck Leather",
    dial: "Warm Dune Beige",
    material: "Sandblasted Steel",
    waterResistance: "50m",
    badge: "Trending",
    tagline: "Tactile desert hues inspired by coastal dunes and raw concrete.",
    description: "Matte sandblasted case finish with zero glare. The soft nubuck band feels like velvet and acquires a beautiful personal patina over months of wear.",
    aiMatchScore: 91,
    aiReason: "Warm sand neutral pairs effortlessly with linen, oversized tees, and minimal streetwear.",
    occasion: ["Casual", "Weekend"],
    colors: ["#D9C9B8", "#B08D6B"]
  },
  {
    id: "WRT-021",
    num: "21",
    brand: "ORBITA",
    model: "Nightline",
    price: 5299,
    originalPrice: 6699,
    rating: 4.8,
    reviewsCount: 110,
    image: "./assets/products/watch-21.png",
    category: "Unisex",
    gender: "Unisex",
    movement: "Quartz",
    style: "Minimal",
    caseSize: "40mm",
    strap: "Black PVD Oyster Link",
    dial: "Midnight Matte",
    material: "PVD Stainless Steel",
    waterResistance: "50m",
    badge: "Best Seller",
    tagline: "Architectural stealth link watch with micro-beveled bezel edges.",
    description: "Equipped with a solid-link metal bracelet coated in satin PVD black. Clean indices and needle hands ensure instant legibility without distraction.",
    aiMatchScore: 94,
    aiReason: "Versatile dark metal profile suitable for tech workplaces and nocturnal social outings.",
    occasion: ["Office", "Casual", "Evening"],
    colors: ["#171717", "#000000"]
  },
  {
    id: "WRT-022",
    num: "22",
    brand: "ORBITA",
    model: "Coast Blue",
    price: 4599,
    originalPrice: 5799,
    rating: 4.6,
    reviewsCount: 65,
    image: "./assets/products/watch-22.png",
    category: "Unisex",
    gender: "Unisex",
    movement: "Quartz",
    style: "Casual",
    caseSize: "41mm",
    strap: "Navy Ribbed Rubber",
    dial: "Ocean Cobalt",
    material: "Stainless Steel",
    waterResistance: "100m",
    badge: "Water Ready",
    tagline: "100-meter waterproof companion for coastal getaways and water sports.",
    description: "Engineered with a screw-down crown and hydrophobic ribbed silicone band that sheds water instantly. Crisp blue face matches the summer horizon.",
    aiMatchScore: 89,
    aiReason: "Genuine water resistance and sporty colorway make it the ideal companion for poolside and active weekends.",
    occasion: ["Weekend", "Outdoor", "Travel"],
    colors: ["#1B365D", "#4A90E2"]
  },
  {
    id: "WRT-023",
    num: "23",
    brand: "ORBITA",
    model: "Studio White",
    price: 4299,
    originalPrice: 5499,
    rating: 4.7,
    reviewsCount: 84,
    image: "./assets/products/watch-23.png",
    category: "Unisex",
    gender: "Unisex",
    movement: "Quartz",
    style: "Fashion",
    caseSize: "38mm",
    strap: "Chalk White Leather",
    dial: "Optic White",
    material: "Polished Steel",
    waterResistance: "30m",
    badge: "Clean Style",
    tagline: "Pristine gallery-wall white with high-contrast obsidian typography.",
    description: "Like a gallery exhibition on your wrist. High-contrast black hands float over a paper-white dial face, flanked by clean silver lugs and white topstitching.",
    aiMatchScore: 91,
    aiReason: "Striking monochrome contrast that stands out against dark winter jackets or bright summer outfits.",
    occasion: ["Casual", "Creative"],
    colors: ["#FFFFFF", "#111111"]
  },
  {
    id: "WRT-024",
    num: "24",
    brand: "ORBITA",
    model: "Slate Mesh",
    price: 5499,
    originalPrice: 6899,
    rating: 4.8,
    reviewsCount: 105,
    image: "./assets/products/watch-24.png",
    category: "Unisex",
    gender: "Unisex",
    movement: "Quartz",
    style: "Minimal",
    caseSize: "40mm",
    strap: "Anthracite Mesh",
    dial: "Graphite Grey",
    material: "Ion-Plated Steel",
    waterResistance: "50m",
    badge: "Popular",
    tagline: "Understated smoke-grey tonal palette with magnetic Milanese closure.",
    description: "Occupying the sophisticated middle ground between harsh black and bright silver. The graphite brushed dial creates subtle depth without heavy shadows.",
    aiMatchScore: 93,
    aiReason: "Anthracite grey tone is universally compatible with business attire and modern casual styling.",
    occasion: ["Office", "Casual", "Weekend"],
    colors: ["#4A4A4A", "#707070"]
  },
  {
    id: "WRT-025",
    num: "25",
    brand: "VANTA",
    model: "Apex Chrono",
    price: 9999,
    originalPrice: 12999,
    rating: 4.9,
    reviewsCount: 220,
    image: "./assets/products/watch-25.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Chronograph",
    caseSize: "44mm",
    strap: "Solid Rose & Black Bracelet",
    dial: "Multi-layered Chrono",
    material: "316L Stainless Steel",
    waterResistance: "100m",
    badge: "Top Seller",
    tagline: "Motor-inspired high-speed timing with rose gold knurled crown.",
    description: "A powerhouse wrist presence. The Apex Chrono features a multi-tiered dial with textured sub-registers, tachymeter scale, and tactile piston pushers for track timing.",
    aiMatchScore: 95,
    aiReason: "Bold mechanical architecture delivers commanding presence for business leaders and motorsport enthusiasts.",
    occasion: ["Formal", "Travel", "Weekend"],
    colors: ["#B08D6B", "#171717"]
  },
  {
    id: "WRT-026",
    num: "26",
    brand: "VANTA",
    model: "Racer Black",
    price: 7999,
    originalPrice: 9999,
    rating: 4.7,
    reviewsCount: 145,
    image: "./assets/products/watch-26.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Sport",
    caseSize: "43mm",
    strap: "Perforated Racing Leather",
    dial: "Carbon Black & Red",
    material: "Black DLC Steel",
    waterResistance: "100m",
    badge: "Sport Pick",
    tagline: "High-octane red accents with breathable rally-hole strap.",
    description: "Inspired by vintage endurance racing steering wheels. Breathable perforated black leather with scarlet edge-paint, housing a high-accuracy chronograph movement.",
    aiMatchScore: 91,
    aiReason: "Dynamic racing aesthetic injects energy into dark denim, leather jackets, and weekend track days.",
    occasion: ["Weekend", "Casual", "Sport"],
    colors: ["#111111", "#C53030"]
  },
  {
    id: "WRT-027",
    num: "27",
    brand: "VANTA",
    model: "Velocity Steel",
    price: 8499,
    originalPrice: 10499,
    rating: 4.8,
    reviewsCount: 160,
    image: "./assets/products/watch-27.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Sport",
    caseSize: "42mm",
    strap: "Stainless Steel Oyster",
    dial: "Sunray Cobalt Blue",
    material: "Stainless Steel",
    waterResistance: "100m",
    badge: "Trending",
    tagline: "Vibrant blue sunray face enclosed in rugged bevelled steel shoulders.",
    description: "The classic luxury sport archetype re-imagined. Sapphire-coated mineral glass protects an intense cobalt dial with luminescent hands that glow green in darkness.",
    aiMatchScore: 94,
    aiReason: "Versatile luxury sports watch profile that dresses up with a blazer and down with swim trunks.",
    occasion: ["Office", "Weekend", "Travel"],
    colors: ["#1A365D", "#CBD5E0"]
  },
  {
    id: "WRT-028",
    num: "28",
    brand: "VANTA",
    model: "Pulse Red",
    price: 6999,
    originalPrice: 8799,
    rating: 4.6,
    reviewsCount: 74,
    image: "./assets/products/watch-28.png",
    category: "Unisex",
    gender: "Unisex",
    movement: "Quartz",
    style: "Unisex",
    caseSize: "41mm",
    strap: "Crimson Silicone",
    dial: "Ruby Sunburst",
    material: "Anodized Black Steel",
    waterResistance: "50m",
    badge: "Bold Color",
    tagline: "Unapologetic scarlet dial designed for bold fashion statements.",
    description: "A head-turning statement watch. Saturated crimson dial flanked by a dark matte case and matching flexible silicone strap that withstands rain and gym sweat.",
    aiMatchScore: 87,
    aiReason: "High-contrast visual centerpiece for creative professionals who dress in predominantly black or monochrome.",
    occasion: ["Casual", "Creative"],
    colors: ["#9B1C1C", "#111111"]
  },
  {
    id: "WRT-029",
    num: "29",
    brand: "VANTA",
    model: "Trail Green",
    price: 7499,
    originalPrice: 9299,
    rating: 4.7,
    reviewsCount: 88,
    image: "./assets/products/watch-29.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Outdoor",
    caseSize: "42mm",
    strap: "Woven Green Nylon",
    dial: "Forest Green",
    material: "Bead-Blasted Steel",
    waterResistance: "100m",
    badge: "Outdoor",
    tagline: "Mil-spec ballistic nylon with quick-drying moisture-wicking weave.",
    description: "Engineered for durability on the trail. Heavy-gauge field hands, 100m water resistance, and a non-reflective matte bead-blasted stainless steel case.",
    aiMatchScore: 89,
    aiReason: "Utilitarian green tone harmonizes with wax jackets, flannels, and rugged outdoor excursions.",
    occasion: ["Outdoor", "Travel", "Weekend"],
    colors: ["#2F4F2F", "#1A1A1A"]
  },
  {
    id: "WRT-030",
    num: "30",
    brand: "VANTA",
    model: "Carbon X",
    price: 8999,
    originalPrice: 11299,
    rating: 4.8,
    reviewsCount: 135,
    image: "./assets/products/watch-30.png",
    category: "Men",
    gender: "Men",
    movement: "Quartz",
    style: "Sport",
    caseSize: "43mm",
    strap: "Solid Carbon PVD Steel",
    dial: "3D Textured Carbon",
    material: "PVD Coated 316L",
    waterResistance: "100m",
    badge: "Popular",
    tagline: "Woven twill carbon texture dial under scratch-resistant sapphire.",
    description: "The dial captures light across hundreds of micro-facets mimicking woven carbon fiber. Fitted on a stealth black link bracelet with a concealed butterfly clasp.",
    aiMatchScore: 92,
    aiReason: "High-tech composite feel ideal for enthusiasts who value modern materials and industrial design.",
    occasion: ["Weekend", "Sport", "Office"],
    colors: ["#171717", "#2D3748"]
  },
  {
    id: "WRT-031",
    num: "31",
    brand: "NORDEN",
    model: "Automatic One",
    price: 16999,
    originalPrice: 21999,
    rating: 4.9,
    reviewsCount: 340,
    image: "./assets/products/watch-31.png",
    category: "Men",
    gender: "Men",
    movement: "Automatic",
    style: "Automatic",
    caseSize: "41mm",
    strap: "Solid 3-Link Steel",
    dial: "Deep Royal Sunburst",
    material: "Surgical 316L Steel",
    waterResistance: "100m",
    badge: "Luxury Automatic",
    tagline: "Self-winding 24-jewel Japanese mechanical movement with 42h reserve.",
    description: "The pinnacle of everyday mechanical luxury. No battery required; winds automatically with your natural wrist motion. Sapphire crystal front and rear, high-beat second hand sweep.",
    aiMatchScore: 99,
    aiReason: "Highest recommendation for the classic luxury watch collector: mechanical integrity, stunning blue dial, and lifetime durability.",
    occasion: ["Office", "Formal", "Luxury"],
    colors: ["#1E3A8A", "#D1D5DB"]
  },
  {
    id: "WRT-032",
    num: "32",
    brand: "NORDEN",
    model: "Skeleton Arc",
    price: 19999,
    originalPrice: 24999,
    rating: 5.0,
    reviewsCount: 410,
    image: "./assets/products/watch-32.png",
    category: "Men",
    gender: "Men",
    movement: "Automatic",
    style: "Automatic",
    caseSize: "42mm",
    strap: "Polished Steel Bracelet",
    dial: "Open-worked Skeleton",
    material: "316L Stainless Steel",
    waterResistance: "50m",
    badge: "Masterpiece",
    tagline: "Exhibition open-worked dial showcasing beating balance wheel and gears.",
    description: "A mechanical sculpture. The skeletonized caliber reveals the rhythmic pulse of the hairspring and intricate gear train through double anti-reflective sapphire glass.",
    aiMatchScore: 98,
    aiReason: "Ultimate conversational horological statement that celebrates centuries of mechanical watchmaking art.",
    occasion: ["Luxury", "Evening", "Formal"],
    colors: ["#E5E7EB", "#B45309"]
  },
  {
    id: "WRT-033",
    num: "33",
    brand: "NORDEN",
    model: "Midnight Auto",
    price: 17999,
    originalPrice: 22499,
    rating: 4.8,
    reviewsCount: 195,
    image: "./assets/products/watch-33.png",
    category: "Men",
    gender: "Men",
    movement: "Automatic",
    style: "Automatic",
    caseSize: "41mm",
    strap: "Black Italian Leather",
    dial: "Lacquered Jet Black",
    material: "Surgical Stainless Steel",
    waterResistance: "50m",
    badge: "Collector",
    tagline: "Glossy black lacquer dial with razor-thin rhodium indices and rotor sweep.",
    description: "Deep black enamel lacquer dial paired with hand-stitched Tuscan leather. The decorated mechanical rotor sweeps smoothly across the rear exhibition window.",
    aiMatchScore: 95,
    aiReason: "Epitome of sartorial discretion: pristine black-tie styling powered by traditional horology.",
    occasion: ["Formal", "Luxury", "Evening"],
    colors: ["#000000", "#E5E7EB"]
  },
  {
    id: "WRT-034",
    num: "34",
    brand: "NORDEN",
    model: "Heritage 38",
    price: 15999,
    originalPrice: 19999,
    rating: 4.9,
    reviewsCount: 180,
    image: "./assets/products/watch-34.png",
    category: "Men",
    gender: "Men",
    movement: "Automatic",
    style: "Classic",
    caseSize: "38mm",
    strap: "Tan Horween Leather",
    dial: "Vintage Warm Cream",
    material: "Rose Gold PVD Steel",
    waterResistance: "50m",
    badge: "Heritage",
    tagline: "Golden era 38mm proportions inspired by 1950s gentlemen's chronometers.",
    description: "At a restrained 38mm, the Heritage 38 slips under any cuff effortlessly. The box-domed sapphire crystal imparts subtle vintage distortion at oblique angles.",
    aiMatchScore: 96,
    aiReason: "Classic 38mm proportions are widely considered the golden ratio for tailored elegance and wrist balance.",
    occasion: ["Formal", "Office", "Weekend"],
    colors: ["#F6F1E9", "#C89B5B"]
  },
  {
    id: "WRT-035",
    num: "35",
    brand: "NORDEN",
    model: "Open Heart",
    price: 14999,
    originalPrice: 18999,
    rating: 4.8,
    reviewsCount: 165,
    image: "./assets/products/watch-35.png",
    category: "Men",
    gender: "Men",
    movement: "Automatic",
    style: "Automatic",
    caseSize: "40mm",
    strap: "Alligator-Grain Brown Leather",
    dial: "Parchment with Escapement Cutout",
    material: "Rose Gold PVD",
    waterResistance: "50m",
    badge: "Luxury Pick",
    tagline: "Dial aperture revealing the beating heart of the mechanical balance wheel.",
    description: "The Open Heart allows you to observe the perpetual oscillation of the balance spring at 21,600 vibrations per hour while retaining a legible dress dial.",
    aiMatchScore: 93,
    aiReason: "Combines classic dress watch styling with the mesmerizing mechanical motion of an open balance wheel.",
    occasion: ["Luxury", "Formal"],
    colors: ["#FAF5EF", "#9A3412"]
  },
  {
    id: "WRT-036",
    num: "36",
    brand: "NORDEN",
    model: "Bronze Field",
    price: 18499,
    originalPrice: 22999,
    rating: 4.9,
    reviewsCount: 140,
    image: "./assets/products/watch-36.png",
    category: "Men",
    gender: "Men",
    movement: "Automatic",
    style: "Outdoor",
    caseSize: "42mm",
    strap: "Distressed Saddle Leather",
    dial: "Matte Olive Field",
    material: "CuSn8 Marine Bronze",
    waterResistance: "100m",
    badge: "Collector",
    tagline: "Solid marine bronze case that develops a unique natural patina with you.",
    description: "Crafted from genuine marine-grade CuSn8 bronze, this watch oxidizes uniquely depending on your adventures, humidity, and wear, creating a one-of-a-kind heirloom.",
    aiMatchScore: 94,
    aiReason: "Evolving bronze patina offers unmatched storytelling and authenticity for rugged lifestyle connoisseurs.",
    occasion: ["Outdoor", "Travel", "Weekend"],
    colors: ["#854D0E", "#27272A"]
  },
  {
    id: "WRT-037",
    num: "37",
    brand: "PULSE",
    model: "Pulse One",
    price: 5999,
    originalPrice: 7999,
    rating: 4.7,
    reviewsCount: 280,
    image: "./assets/products/watch-37.png",
    category: "Smart Watches",
    gender: "Unisex",
    movement: "Smart Digital",
    style: "Smart",
    caseSize: "44mm",
    strap: "Obsidian Silicone",
    dial: "Always-on AMOLED",
    material: "Aerospace Aluminum",
    waterResistance: "50m",
    badge: "Best Seller",
    tagline: "Ultra-crisp 1.43\" AMOLED display with 7-day battery and biometric suite.",
    description: "PULSE bridges smartwatch intelligence with luxury industrial aesthetics. Features continuous heart-rate, SpO2, sleep stages, 100+ workout modes, and notifications.",
    aiMatchScore: 95,
    aiReason: "Best recommendation for health-conscious professionals seeking smart connectivity without sacrificing wrist style.",
    occasion: ["Sport", "Active", "Office"],
    colors: ["#000000", "#3B82F6"]
  },
  {
    id: "WRT-038",
    num: "38",
    brand: "PULSE",
    model: "Pulse Active",
    price: 6999,
    originalPrice: 8999,
    rating: 4.8,
    reviewsCount: 190,
    image: "./assets/products/watch-38.png",
    category: "Smart Watches",
    gender: "Unisex",
    movement: "Smart Digital",
    style: "Smart",
    caseSize: "42mm",
    strap: "Lilac Fluororubber",
    dial: "Vibrant Curved AMOLED",
    material: "Lightweight Aluminum",
    waterResistance: "50m",
    badge: "Fitness Pick",
    tagline: "Sweatproof ergonomic band with dual-frequency GPS and recovery metrics.",
    description: "Designed for runners, yogis, and fitness pioneers. The soft lilac fluororubber band resists moisture while the curved glass conforms comfortably during movement.",
    aiMatchScore: 92,
    aiReason: "Combines active tracking features with a gentle, refreshing colorway that looks great in the gym and at lunch.",
    occasion: ["Active", "Sport", "Casual"],
    colors: ["#A78BFA", "#F3F4F6"]
  },
  {
    id: "WRT-039",
    num: "39",
    brand: "PULSE",
    model: "Pulse Pro",
    price: 8999,
    originalPrice: 11999,
    rating: 4.9,
    reviewsCount: 310,
    image: "./assets/products/watch-39.png",
    category: "Smart Watches",
    gender: "Men",
    movement: "Smart Digital",
    style: "Smart",
    caseSize: "46mm",
    strap: "Tactical Forest Green Band",
    dial: "High-Nit Sunlight AMOLED",
    material: "Titanium & Ceramic",
    waterResistance: "50m",
    badge: "Flagship",
    tagline: "Titanium bezel, offline maps, 14-day battery life, and Bluetooth calling.",
    description: "The ultimate rugged smartwatch. Built with a tough titanium bezel ring, ceramic sensor backing, dual microphones for crisp wrist calls, and military-grade drop resistance.",
    aiMatchScore: 96,
    aiReason: "Uncompromising smartwatch durability with battery life that lasts through multi-day backcountry trails.",
    occasion: ["Outdoor", "Sport", "Travel"],
    colors: ["#14532D", "#1F2937"]
  },
  {
    id: "WRT-040",
    num: "40",
    brand: "PULSE",
    model: "Pulse Lite",
    price: 4999,
    originalPrice: 6499,
    rating: 4.6,
    reviewsCount: 150,
    image: "./assets/products/watch-40.png",
    category: "Smart Watches",
    gender: "Unisex",
    movement: "Smart Digital",
    style: "Smart",
    caseSize: "40mm",
    strap: "Cream Silicone",
    dial: "Retina Color Display",
    material: "Reinforced Polymer",
    waterResistance: "30m",
    badge: "Value Pick",
    tagline: "Featherweight 32g design with all essential fitness and wellness tracking.",
    description: "Smartwatch essentials in a featherlight package. Soft cream band and bezel, customizable watch faces, step tracking, breathing exercises, and music controls.",
    aiMatchScore: 90,
    aiReason: "Lightweight, accessible entry point into smart health tracking with a clean, friendly aesthetic.",
    occasion: ["Casual", "Active", "Daily"],
    colors: ["#FDFBF7", "#E2E8F0"]
  }
];

// Curated Editorial Collections
const COLLECTIONS = [
  {
    id: "quiet-luxury",
    title: "Quiet Luxury",
    subtitle: "Understated excellence in precious metals and refined dials.",
    description: "No loud logos. Just impeccable proportions, warm champagne metals, and hand-finished details that whisper sophistication.",
    heroWatchId: "WRT-014",
    itemIds: ["WRT-003", "WRT-009", "WRT-013", "WRT-014", "WRT-034", "WRT-035"],
    bannerTag: "EDITORIAL SELECTION"
  },
  {
    id: "everyday-icons",
    title: "Everyday Icons",
    subtitle: "Enduring timepieces built for daily rotation and effortless style.",
    description: "Watches you can put on in the dark and wear with anything. Balanced, resilient, and relentlessly reliable.",
    heroWatchId: "WRT-001",
    itemIds: ["WRT-001", "WRT-002", "WRT-011", "WRT-017", "WRT-018", "WRT-024"],
    bannerTag: "DAILY DRIVERS"
  },
  {
    id: "mechanical-souls",
    title: "Mechanical Souls",
    subtitle: "Self-winding calibers and exhibition balance wheels.",
    description: "For those who find poetry in miniature mechanics. Zero batteries, 28,800 beats per hour, and intricate open-worked architecture.",
    heroWatchId: "WRT-032",
    itemIds: ["WRT-005", "WRT-031", "WRT-032", "WRT-033", "WRT-034", "WRT-035", "WRT-036"],
    bannerTag: "AUTOMATIC ONLY"
  },
  {
    id: "built-for-weekend",
    title: "Built for the Weekend",
    subtitle: "Water resistance, tactical straps, and sport chronographs.",
    description: "From coastal surf to gravel trails, these watches feature screw-down crowns, reinforced rubber, and split-second timers.",
    heroWatchId: "WRT-025",
    itemIds: ["WRT-006", "WRT-019", "WRT-022", "WRT-025", "WRT-026", "WRT-027", "WRT-029", "WRT-030"],
    bannerTag: "ADVENTURE & SPORT"
  },
  {
    id: "minimal-by-design",
    title: "Minimal by Design",
    subtitle: "Bauhaus geometry and pure monochrome dials.",
    description: "Every unnecessary element removed until only time and pure form remain. Sharp baton hands and clean satin cases.",
    heroWatchId: "WRT-017",
    itemIds: ["WRT-001", "WRT-011", "WRT-017", "WRT-018", "WRT-021", "WRT-023"],
    bannerTag: "BAUHAUS MINIMAL"
  },
  {
    id: "under-20k",
    title: "Fine Horology Under ₹20,000",
    subtitle: "Automatic and exhibition movements at accessible price points.",
    description: "Democratizing high-end watchmaking. Real automatic calibers, solid end-links, and sapphire crystals without the luxury markups.",
    heroWatchId: "WRT-031",
    itemIds: ["WRT-005", "WRT-031", "WRT-033", "WRT-034", "WRT-035", "WRT-036"],
    bannerTag: "VALUE HOROLOGY"
  }
];

// Curated Brands
const BRANDS = [
  {
    name: "AUREN",
    country: "Boutique Series",
    established: "Est. 2021",
    headline: "Architectural Precision & Pure Dials",
    description: "Auren crafts modern architectural timepieces characterized by ultra-slim cases, uncluttered dials, and surgical-grade stainless steel.",
    priceRange: "₹4,499 – ₹14,999",
    featuredWatchId: "WRT-005",
    styles: ["Minimal", "Classic", "Automatic", "Chronograph"],
    watchCount: 8
  },
  {
    name: "VELA",
    country: "Elegance Series",
    established: "Est. 2022",
    headline: "Jewelry-Grade Warmth & Feminine Poise",
    description: "Vela harmonizes Italian jewelry aesthetics with modern horology. Renowned for iridescent mother-of-pearl dials and fluid Milanese mesh.",
    priceRange: "₹4,799 – ₹8,499",
    featuredWatchId: "WRT-009",
    styles: ["Dress", "Fashion", "Minimal", "Classic"],
    watchCount: 8
  },
  {
    name: "ORBITA",
    country: "Nordic Series",
    established: "Est. 2020",
    headline: "Bauhaus Simplicity for Every Wrist",
    description: "Orbita strips away the excessive. Clean unisex proportions, sustainable packaging, and medical-grade materials designed for seamless daily rotation.",
    priceRange: "₹3,999 – ₹5,499",
    featuredWatchId: "WRT-018",
    styles: ["Minimal", "Casual", "Lifestyle", "Fashion"],
    watchCount: 8
  },
  {
    name: "VANTA",
    country: "Performance Series",
    established: "Est. 2019",
    headline: "High-Octane Chronographs & Bold Composites",
    description: "Drawing inspiration from motorsport instrumentation, Vanta produces tactile chronographs, carbon-weave dials, and 100m water-resistant tool watches.",
    priceRange: "₹6,999 – ₹9,999",
    featuredWatchId: "WRT-025",
    styles: ["Chronograph", "Sport", "Outdoor"],
    watchCount: 6
  },
  {
    name: "NORDEN",
    country: "Horology Series",
    established: "Est. 2018",
    headline: "Mechanical Soul & Exhibition Artistry",
    description: "Norden is dedicated exclusively to mechanical and automatic movements. Featuring 24-jewel calibers, skeletonized dials, and authentic marine bronze.",
    priceRange: "₹14,999 – ₹19,999",
    featuredWatchId: "WRT-032",
    styles: ["Automatic", "Skeleton", "Classic", "Field"],
    watchCount: 6
  },
  {
    name: "PULSE",
    country: "Connected Series",
    established: "Est. 2023",
    headline: "Intelligent AMOLED Technology in Luxury Shells",
    description: "Pulse bridges smartwatch intelligence with luxury timepiece finishing. Titanium bezels, always-on vibrant AMOLED displays, and comprehensive wellness tracking.",
    priceRange: "₹4,999 – ₹8,999",
    featuredWatchId: "WRT-037",
    styles: ["Smart Digital", "Active", "Sport"],
    watchCount: 4
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PRODUCTS, COLLECTIONS, BRANDS };
}
